name: release
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  packages: write

jobs:
  deb-release:
    name: Create DEB release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build DEB
        run: |
          mkdir -p build
          dpkg-deb --build nagios-plugins-ets-1.4 build/nagios-plugins-ets-1.4.deb

      - name: Upload DEB as artifact
        uses: actions/upload-artifact@v3
        with:
          name: nagios-plugins-ets-1.4.deb
          path: build/nagios-plugins-ets-1.4.deb

      - name: Release DEB
        uses: softprops/action-gh-release@v1
        with:
          files: build/nagios-plugins-ets-1.4.deb
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
