name: Build and Release DEB Package

on:
  push:

jobs:
  rpm-release:
    name: Create DEB release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install debuild
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            devscripts \
            build-essential \
            lintian \
            debhelper

      - name: Download the source tarball
        run: |
          wget -O ../nagios-plugins-ets_1.4.orig.tar.gz https://github.com/ucsd-ets/nagios-plugins-ets/archive/refs/tags/1.2.tar.gz
          tar zxvf ../nagios-plugins-ets_1.4.orig.tar.gz --strip-components=1

      - name: Build DEB package
        run: |
          debuild -us -uc

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nagios-plugins-ets_amd64.deb
          path: |
            ../nagios-plugins-ets_1.4_amd64.deb
