name: Build and Release DEB Package

on:
  push:
    tags:
      - 'v*'  # Trigger on new tags starting with 'v'
permissions:
    contents: write
jobs:
  rpm-release:
    name: Create DEB release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build DEB package
        run: dpkg-deb --build nagios-plugins-ets-1.4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has the right permissions
        with:
          tag_name: ${{ github.ref }}  # Tag that triggered the workflow
          release_name: Release ${{ github.ref }}  # Name of the release
          draft: false
          prerelease: false

      - name: Upload DEB package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has the right permissions
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Upload URL from the create release step
          asset_path: ./nagios-plugins-ets-1.4.deb  # Path to the DEB package
          asset_name: nagios-plugins-ets-1.4.deb  # Name of the asset
          asset_content_type: application/vnd.debian.binary-package  # Content type
